[theme]
theme = "dracula"
[icons]
icons = "awesome6"

[[block]]
block = "focused_window"

[[block]]
block = "net"
device = "wlp1s0"
format = " $icon  $signal_strength $ssid [$ip] ↓$speed_down ↑$speed_up "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization $frequency "

[[block]]
block = "load"
interval = 3
format = " $icon  $1m.eng(w:4)-$5m.eng(w:4)-$15m.eng(w:4) "

[[block]]
block = "backlight"
format = " ☀ $brightness"
[block.theme_overrides]
idle_bg = "#2a6f8c"

[[block]]
block = "sound"

[[block]]
block = "battery"

[[block]]
block = "taskwarrior"
interval = 600
format = " $icon  $count.eng(w:1) open tasks "
format_singular = " $icon  $count.eng(w:1) open task "
format_everything_done = " $icon  nothing to do! "
warning_threshold = 3
critical_threshold = 5 

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R') "
