[theme]
theme = "dracula"
[icons]
icons = "awesome6"

[[block]]
block = "focused_window"

[[block]]
block = "net"
device = "wlp1s0"
format = " $icon\t$signal_strength\t$ssid\t[$ip]\t↓$speed_down\t↑$speed_up "

[[block]]
block = "memory"
format = " $icon\t$mem_used_percents.eng(w:1) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
format = " $icon\t$utilization\t$frequency "

[[block]]
block = "load"
interval = 3
format = " $icon\t$1m.eng(w:4)-$5m.eng(w:4)-$15m.eng(w:4) "

[[block]]
block = "backlight"
format = " ☀ $brightness"
[block.theme_overrides]
idle_bg = "#2a6f8c"

[[block]]
block = "sound"

[[block]]
block = "battery"
format = " $icon\t$percentage"

[[block]]
block = "taskwarrior"
interval = 600
format = " $icon\t$count.eng(w:1) open tasks "
format_singular = " $icon\t$count.eng(w:1) open task "
format_everything_done = " $icon\tnothing to do! "
warning_threshold = 3
critical_threshold = 5 

[[block]]
block = "time"
interval = 60
format = " $icon\t$timestamp.datetime(f:'%a %Y-%m-%d %R') "
